### ISSUE TITLE
Problems installing 'gcloud' components

### ISSUE THREAD

**Issue by usrme** [cashapp/hermit-packages#222]
This stinks of something wrong on my machine, but after wasting far too much time already I am turning here as some sort of sanity check. I am successfully able to install and use `gcloud`, but trying to install a component like `gke-gcloud-auth-plugin` using `gcloud components install ...` fails with a permission error:

```console
$ gcloud components install gke-gcloud-auth-plugin

ERROR: (gcloud.components.install) You cannot perform this action because you do not have permission
to modify the Google Cloud SDK installation directory [/home/usrme/.cache/hermit/pkg/gcloud-405.0.1].

Re-run the command with sudo: sudo /home/usrme/.cache/hermit/pkg/gcloud-405.0.1/bin/gcloud ...
```

Looking at the listed directory I can see that the `gcloud-405.0.1` directory does not have the correct permissions set despite other packages installed through Hermit having them:

```console
$ ls -la /home/usrme/.cache/hermit/pkg
drwx------.  3 usrme usrme   40  6. okt   10:52 azcopy-10.16.1
drwx------.  2 usrme usrme   50  6. okt   13:20 dive-0.10.0
dr-x------.  9 usrme usrme 4096 17. okt   17:41 gcloud-405.0.1
...
```

I can, of course, adjust this manually (`chmod -R u+rwx /home/usrme/.cache/hermit/pkg/gcloud-405.0.1`) which then allows for the installation to finish successfully, but this still begs the question: why are the initial permissions different for `gcloud`?

Also, removing `gcloud` with `hermit uninstall ...` does not remove the underlying directory, which is understandable given the lack of write permissions.

Just in case:

- my `umask` is 0022
- it does not matter if I install an older version of `gcloud` as the permissions are still the same

**Comment by usrme** [comment]
I am tempted to create a separate manifest for this plugin, but this seems excessive (though I am partial to having things like this installed and managed through Hermit) and bothersome seeing as the download URLs for these components do not include version numbers but rather build numbers, which would make auto-versioning a pain if not impossible.

**Comment by alecthomas** [comment]
Packages are immutable by default by design. This is to prevent mutable state "leaking" between environments. That said, some packages can't operate without being mutable. This default behaviour can be changed by setting `mutable = true`.

I think ideally it would be preferable if the components were also packages, but I don't know if that's practical. The upside of them being packages is that Hermit can manage everything. Does the above package that you wrote work? I'm also not sure about the version compatibility between gcloud and the components.

**Comment by alecthomas** [comment]
I have no idea why azcopy and dive are writeable on your machine. Hermit makes packages read-only, and all the packages on my machine are read-only. Making gcloud mutable seems reasonable to me.

**Comment by usrme** [comment]
How very interesting about the difference between our machines' default states. I'll do some testing with the `mutable` attribute to see if that changes anything. Thanks for your time!

**Comment by alecthomas** [comment]
Feel free to send a PR changing gcloud to mutable, though one caveat is that Hermit won't retroactively change an installed package, so any existing gcloud installed will still be immutable.
