### ISSUE TITLE
rust packages broken by wrong digests

### ISSUE THREAD

**Issue by OmarTawfik** [cashapp/hermit-packages#235]
Several (all?) Rust projects are now suddenly broken with the following error:

```log
fatal:hermit: https://static.rust-lang.org/dist/rust-1.64.0-x86_64-unknown-linux-gnu.tar.xz: https://static.rust-lang.org/dist/rust-1.64.0-x86_64-unknown-linux-gnu.tar.xz: checksum bd69e42f6cfe3ba96d781ad0b4095ddac4f0fc31c1af445018edf6f0aba543e4 should have been b51d1e2f752f58d02d781566f3e3ac4da0a666896ebba49d70f404dbaf312d7c
```

I traced the issue to https://github.com/cashapp/hermit-packages/commit/900d52181d111334f096afe9a909966a3e483d3d (cc @alecthomas). I think there is a bug in whichever import script it is using, which made it put the same digest in `rust.hcl`, for both `apple-darwin.tar.xz` and `unknown-linux-gnu.tar.xz`, for all versions. 

To unblock these projects, I tried locking the `hermit-packages` source version, which failed as well. I filed a separate bug for: https://github.com/cashapp/hermit/issues/342

 So, for now, I manually forked `rust.hcl` (as a private package) to unblock these projects.

**Comment by alecthomas** [comment]
Ah I missed "all versions". Interesting 🤔

**Comment by alecthomas** [comment]
Ah I see what happened, I forgot to add the arch interpolation to the `sha256-sources` entry when I generated these digests:

```
// sha256-source = "https://static.rust-lang.org/dist/rust-${version}-${xarch}-apple-darwin.tar.xz.sha256"
```

**Comment by OmarTawfik** [comment]
Thank you!

**Comment by alecthomas** [comment]
Thanks for the report, and apologies for the bug!
