### ISSUE TITLE
ffmpeg package hasn't picked up 6.0.0

### ISSUE THREAD

**Issue by lox** [cashapp/hermit-packages#431]
I was just looking into adding `ffprobe` to the [ffmpeg package](https://github.com/cashapp/hermit-packages/blob/f5c0ab3b417cd57f918ef89af3b84efd5b8e915a/ffmpeg.hcl) and I noticed it hasn't added the most recent 6.0 release:

https://github.com/eugeneware/ffmpeg-static/releases

I wonder if this is because it was 6.0 vs 6.0.0?

**Comment by alecthomas** [comment]
That shouldn't be a problem, it's more likely that the binary names changed. You can check with `hermit manifest auto-version ffmpeg.hcl --add-digests`

**Comment by lox** [comment]
Yup, you were right:

```
warn:ffmpeg: Retrying. Failed to download any of https://github.com/eugeneware/ffmpeg-static/releases/download/b6.0/linux-x64.gz on attempt 1/3: download failed: 404 Not Found (404)
warn:ffmpeg: Retrying. Failed to download any of https://github.com/eugeneware/ffmpeg-static/releases/download/b6.0/linux-x64.gz on attempt 2/3: download failed: 404 Not Found (404)
warn:ffmpeg: Failed to download any of https://github.com/eugeneware/ffmpeg-static/releases/download/b6.0/linux-x64.gz on attempt 3/3: download failed: 404 Not Found (404)
```

**Comment by lox** [comment]
Is it possible to override binary names for a version and onwards?

**Comment by alecthomas** [comment]
Yeah, the pattern is:

1. Create a version block for all the old versions, using the old naming convention - probably moving all the vars/source overrides into the block.
2. Create a new block with auto-versioning that uses the globally scoped new naming convention.

LMK if that doesn't make sense.

**Comment by lox** [comment]
Done in #433 (I think) @alecthomas

**Comment by alecthomas** [comment]
Awesome, thanks @lox
