### ISSUE TITLE
ruby uses homebrew's "package" of ruby which is not intended to be used in this fashion

### ISSUE THREAD

**Issue by jufemaiz** [cashapp/hermit-packages#472]
https://github.com/Homebrew/homebrew-portable-ruby/issues/185#issuecomment-2024655678

**Comment by alecthomas** [comment]
What issue does this cause?

**Comment by jufemaiz** [comment]
Critical part, beyond the author's specifically described "don't use this" warning, would be the lack of ongoing support of more up-to-date releases (for example, the linked ticket explicitly rejected option to bump release to current major release. AWS lambda ruby for instance is [on Ruby 3.2](https://aws.amazon.com/blogs/compute/ruby-3-2-runtime-now-available-in-aws-lambda/) with no Ruby 3.1 support at all)

Perhaps there's scope for an alternative solution if a pathway is open like the python project https://github.com/indygreg/python-build-standalone ?

**Comment by alecthomas** [comment]
Hermit doesn't care where the tarballs come from, but currently these are the only portable Ruby builds available so there's no choice.
