### ISSUE TITLE
Automated deleting of unavailable versions

### ISSUE THREAD

**Issue by jufemaiz** [cashapp/hermit-packages#532]
Is the deletion of unavailable versions of a package something that has been considered? I'm raising this as due to the approach adopted by Atlas (ref: https://github.com/ariga/atlas/issues/3213) wherein only two minor versions + any other releases less than six months are maintained. At this stage the cadence of minor release is around one per month.

**Comment by alecthomas** [comment]
No, and we will not support that model.

If you want to track the "latest" version use a channel such as `@latest`.
