### ISSUE TITLE
Enable Folks to contribute

### ISSUE THREAD

**Issue by seniledeveloper** [cashapp/hermit-packages#96]
Context: https://cashapp.github.io/hermit/packaging/tutorial/

> At this point you can (and should!) contribute the package back to the community via a PR.
Lies! When I tried to I received:
- remote: No anonymous write access (and then after logging in)
- remote: Permission to cashapp/hermit-packages.git denied to seniledeveloper. fatal: unable to access 'https://github.com/cashapp/hermit-packages/': The requested URL returned error: 403

**Comment by alecthomas** [comment]
PR means Pull Request. Fork the repository, make the change in your fork, then GitHub will let you create one to contribute. This is the standard contribution path on GitHub.

**Comment by seniledeveloper** [comment]
> PR means Pull Request.

I am the living embodiment of surprise. In other news. Found [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

> Note: To open a pull request in a public repository, you must have write access to the head or the source branch or, for organization-owned repositories, you must be a member of the organization that owns the repository to open a pull request.

and

> If you want to create a new branch for your pull request and do not have write permissions to the repository, you can fork the repository first. For more information, see "Creating a pull request from a fork" and "About forks."

So if the intention is to enable others to contribute to the hermit packages repo then perhaps this should be made clear in the docs or changed in some way.

**Comment by alecthomas** [comment]
The fork+PR work flow is well established. I personally don't think it needs any further clarification but if you do, feel free to use that workflow to send a PR improving the documentation.
